version: "3.7"

services:
  db:
    image: "${SQL_IMAGE_NAME}:${SQL_IMAGE_VERSION}"
    volumes:
      - ${SQL_VOLUME}
    restart: always
    env_file:
      - .envdb

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - .envphpadmin

  nginx:
    image: "${NGINX_IMAGE_NAME}:${NGINX_IMAGE_VERSION}"
    container_name: web-nginx
    volumes:
      - ${NGINX_VOLUME}
      - "./docker-web/www:/usr/share/nginx/html:ro"
    ports:
      - "${NGINX_PORT}:80"
    restart: always
    env_file:
      - .envnginx

volumes:
  db_data: {}
  nginx_data: {}
