version: "3.7"

services:
  db:
    image: "${SQL_IMAGE_NAME}:${SQL_IMAGE_VERSION}"
    volumes:
      - ${SQL_VOLUME}
    restart: always
    env_file:
      - .envdb

  phpmyadmin:
    depends_on:
      - db
      - nginx
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      - .envphpadmin

  nginx:
    depends_on:
      - db
    image: "${NGINX_IMAGE_NAME}:${NGINX_IMAGE_VERSION}"
    container_name: web-nginx
    volumes:
      - ${NGINX_VOLUME}
      - "./docker-web/www:/usr/share/nginx/html:ro"
    ports:
      - "${NGINX_PORT}:80"
    restart: always
    env_file:
      - .envnginx

  st-agent:
    image: sematext/agent:latest
    environment:
      - INFRA_TOKEN=965d16fc-e7d0-46e4-a73c-caa7fec05175
      - REGION=EU
    cap_add:
      - SYS_ADMIN
    restart: always
    volumes:
      - /:/hostfs:ro
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /var/run/:/var/run
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys:/host/sys:ro
      - /dev:/hostfs/dev:ro

volumes:
  db_data: {}
  nginx_data: {}
